### PR TITLE
Remove old tests and create new

### LINKED ISSUE #41: clean up and update unitest
place all tests and examples in `test_treematcher.py`, which should use python unittest module like for other ete3 modules. 

progressively expand test cases

### PR DESCRIPTION
**Pull request by dpliakos**
Treematcher is refactored and old tests do not correspond to the new syntax, so they are removed.
New tests are created.

Fixes  #41

### CODE REVIEW

**Comment by jhcepas** [comment]
is travis supposed to pass here?

**Comment by dpliakos** [comment]
Yes, they should pass and they do locally. the error is while trying to import treematcher module.

**Comment by jhcepas** [comment]
Cannot merge until conflicts are solved.

**Comment by dpliakos** [comment]
These commits are in another pull request ( #52 ). 
I suggest to close this one.

**Comment by jhcepas** [comment]
Ok, you can close it then

**Pull request closed without merging**
